-- PMT - Schéma PostgreSQL versionné
-- Ce script décrit la structure relationnelle actuelle de l'application
-- sans dépendre de la génération Hibernate au démarrage.

BEGIN;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uq_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    start_date DATE,
    owner_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_projects_owner
        FOREIGN KEY (owner_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS project_members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER', 'OBSERVER')),
    joined_at TIMESTAMP(6),
    project_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_project_members_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_members_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uq_project_members_project_user UNIQUE (project_id, user_id)
);

CREATE TABLE IF NOT EXISTS project_invitations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255),
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'MEMBER', 'OBSERVER')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELED')),
    expires_at TIMESTAMP(6),
    accepted_at TIMESTAMP(6),
    canceled_at TIMESTAMP(6),
    project_id BIGINT NOT NULL,
    invited_by_id BIGINT NOT NULL,
    accepted_by_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT uq_project_invitations_token UNIQUE (token),
    CONSTRAINT fk_project_invitations_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_invitations_invited_by
        FOREIGN KEY (invited_by_id) REFERENCES users (id),
    CONSTRAINT fk_project_invitations_accepted_by
        FOREIGN KEY (accepted_by_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS task_board_columns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    display_order INTEGER,
    project_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_task_board_columns_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT uq_task_board_columns_project_name UNIQUE (project_id, name)
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    priority VARCHAR(255) NOT NULL CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH')),
    due_date DATE,
    end_date DATE,
    project_id BIGINT NOT NULL,
    created_by_id BIGINT NOT NULL,
    assigned_to_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_tasks_project
        FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_tasks_created_by
        FOREIGN KEY (created_by_id) REFERENCES users (id),
    CONSTRAINT fk_tasks_assigned_to
        FOREIGN KEY (assigned_to_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS task_histories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type VARCHAR(255) NOT NULL CHECK (action_type IN ('CREATED', 'UPDATED', 'ASSIGNED', 'STATUS_CHANGED', 'COMPLETED')),
    field_name VARCHAR(255) NOT NULL,
    old_value VARCHAR(255),
    new_value VARCHAR(255),
    task_id BIGINT NOT NULL,
    changed_by_id BIGINT NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_task_histories_task
        FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_task_histories_changed_by
        FOREIGN KEY (changed_by_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type VARCHAR(255) NOT NULL CHECK (type IN ('TASK_ASSIGNED', 'INVITATION_SENT')),
    status VARCHAR(255) NOT NULL CHECK (status IN ('SENT', 'READ')),
    message VARCHAR(255) NOT NULL,
    sent_at TIMESTAMP(6),
    user_id BIGINT NOT NULL,
    task_id BIGINT,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_notifications_task
        FOREIGN KEY (task_id) REFERENCES tasks (id)
);

CREATE INDEX IF NOT EXISTS idx_projects_owner_id
    ON projects (owner_id);

CREATE INDEX IF NOT EXISTS idx_project_members_user_id
    ON project_members (user_id);

CREATE INDEX IF NOT EXISTS idx_project_invitations_project_id
    ON project_invitations (project_id);

CREATE INDEX IF NOT EXISTS idx_project_invitations_email
    ON project_invitations (email);

CREATE INDEX IF NOT EXISTS idx_task_board_columns_project_order
    ON task_board_columns (project_id, display_order);

CREATE INDEX IF NOT EXISTS idx_tasks_project_id
    ON tasks (project_id);

CREATE INDEX IF NOT EXISTS idx_tasks_assigned_to_id
    ON tasks (assigned_to_id);

CREATE INDEX IF NOT EXISTS idx_tasks_status
    ON tasks (status);

CREATE INDEX IF NOT EXISTS idx_task_histories_task_id
    ON task_histories (task_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
    ON notifications (user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_task_id
    ON notifications (task_id);

COMMIT;
